theme: jekyll-theme-minimal
title: Welcome to Gonzalo's slice of the internet! 
logo: /images/me.jpg
description: Here I'll be writing about what makes me..well..me! My projects, hobbies, what I've done, what I'm doing, and what I want to do!
